const fs = require('fs');
const lines = fs.readFileSync('server.js', 'utf8').split('\n');
const goodLines = lines.slice(0, 710);
const rest = [
  '          scan_type,',
  '          doctor_name,',
  '          appointment_date,',
  '          appointment_time',
  '        }',
  '      });',
  '    });',
  '  });',
  '});',
  '',
  'app.get("/api/schedules", (req, res) => {',
  '  const sql = "SELECT * FROM scheduled_scans ORDER BY id DESC";',
  '  db.all(sql, [], (err, rows) => {',
  '    if (err) return res.status(500).json({ error: err.message });',
  '    res.json({ data: rows });',
  '  });',
  '});',
  '',
  'app.put("/api/schedule/:schedule_id/status", (req, res) => {',
  '  const { schedule_id } = req.params;',
  '  const { status } = req.body;',
  '  if (!status) return res.status(400).json({ error: "Status is required." });',
  '',
  '  db.run("UPDATE scheduled_scans SET status = ? WHERE schedule_id = ?", [status, schedule_id], function(err) {',
  '    if (err) return res.status(500).json({ error: err.message });',
  '    if (this.changes === 0) return res.status(404).json({ error: "Schedule not found." });',
  '    res.json({ message: `Schedule ${schedule_id} updated to ${status}.` });',
  '  });',
  '});',
  '',
  'app.put("/api/schedule/:schedule_id/reschedule", (req, res) => {',
  '  const { schedule_id } = req.params;',
  '  const { appointment_date, appointment_time } = req.body;',
  '  ',
  '  if (!appointment_date || !appointment_time) {',
  '    return res.status(400).json({ error: "Date and time are required." });',
  '  }',
  '',
  '  db.run(',
  '    "UPDATE scheduled_scans SET appointment_date = ?, appointment_time = ?, status = \'Upcoming\' WHERE schedule_id = ?",',
  '    [appointment_date, appointment_time, schedule_id],',
  '    function(err) {',
  '      if (err) return res.status(500).json({ error: err.message });',
  '      if (this.changes === 0) return res.status(404).json({ error: "Schedule not found." });',
  '      res.json({ message: `Schedule ${schedule_id} rescheduled.` });',
  '    }',
  '  );',
  '});',
  '',
  'server.listen(PORT, HOST, () => {',
  '  console.log(`Server running on http://${HOST}:${PORT}`);',
  '});',
  ''
];
fs.writeFileSync('server.js', [...goodLines, ...rest].join('\n'));
